### ISSUE TITLE
Add support PureEntitiesX

### ISSUE THREAD

**Issue by Karanztez** [AndreasHGK/PocketIslands#5]
The monster cannot lay eggs on the island.

**Comment by andreashgk** [comment]
What?

**Comment by Karanztez** [comment]
Can not find pocketisland maps  ->PureEntitiesX

**Comment by Karanztez** [comment]
https://github.com/RevivalPMMP/PureEntitiesX/blob/master/src/revivalpmmp/pureentities/task/AutoSpawnTask.php

**Comment by andreashgk** [comment]
This is a generator, it should not stop mobs from spawning.
